# Generated by Django 4.2.7 on 2023-11-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tag",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(to="todo.tag"),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
